name: Feature Request
description: Idee/Verbesserung vorschlagen
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Bitte beschreibe kurz den Nutzen und den gewünschten Scope.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Was fehlt dir aktuell?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Vorschlag
      description: Wie soll es aussehen/arbeiten?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false

