-- Tier 1 Migration: Weapons & Armors Normalization

BEGIN TRANSACTION;

-- 1. Ensure Columns Exist (Idempotent)
-- (These are also in migrations.rs, but good to have here for standalone run)
-- SQLite ignores ADD COLUMN if it exists only in newer versions, checking existence is harder in pure SQL script without logic.
-- We assume migrations.rs has run or we run this after app startup.

-- 2. Migrate Core Weapons Scalars
UPDATE core_weapons SET
    source_page = json_extract(data, '$.source_page'),
    range_normal = json_extract(data, '$.thrown_range.normal'),
    range_long = json_extract(data, '$.thrown_range.max')
WHERE data IS NOT NULL;

-- 3. Populate Weapon Properties
INSERT OR IGNORE INTO weapon_properties (id, name, description)
SELECT 
    lower(value), -- ID from name
    value, 
    'Autogenerated from migration'
FROM core_weapons, json_each(json_extract(data, '$.properties'))
WHERE json_valid(data);

-- 4. Populate Weapon Property Mappings
INSERT OR IGNORE INTO core_weapon_property_mappings (weapon_id, property_id)
SELECT 
    w.id, 
    lower(props.value)
FROM core_weapons w, json_each(json_extract(w.data, '$.properties')) props
WHERE json_valid(w.data);

-- 5. Handle "Versatile" (Vielseitig) Parameter
-- Update the mapping with the damage value (e.g., "1d8")
UPDATE core_weapon_property_mappings
SET parameter_value = (
    SELECT json_extract(w.data, '$.versatile_damage')
    FROM core_weapons w
    WHERE w.id = core_weapon_property_mappings.weapon_id
)
WHERE property_id LIKE 'versatile' OR property_id LIKE 'vielseitig';

-- 6. Clean up JSON Data (Optional: Set to NULL or keep for backup?)
-- We will keep it for now until verification is complete.
-- UPDATE core_weapons SET data = NULL;

-- 7. Normalize Armor Properties (if any in JSON)
-- Inspecting core_armors.data might reveal properties like "Stealth Disadvantage" which are already columns.
-- We check for extra properties.

COMMIT;
